import Head from 'next/head';
import Link from 'next/link';
import { authUserServerSideProps } from '../lib/auth';
import { LinkButton, Main, Title } from '../styles/styles';

export const getServerSideProps = async (context) =>
	await authUserServerSideProps(context);

export default function Home(props) {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Main>
				<Title>Hello, {props.givenName}</Title>
				<Link href='/api/auth/logout' passHref>
					<LinkButton>Logout</LinkButton>
				</Link>
			</Main>
		</div>
	);
}
